name: Build, test and deploy Application

on:
  push:
    paths:
      - 'apps/hello_world/**'
      - '.github/workflows/**'
    tags:
      - '*'
  pull_request:
    paths:
      - 'apps/hello_world/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'apps/hello_world/package-lock.json'
      - name: Install dependencies
        run: |
          cd apps/hello_world
          npm install

      - name: Run tests
        run: |
          cd apps/hello_world
          npm test
      - name: Build the application
        run: |
          cd apps/hello_world
          npm run build

  build-and-push-container:
    runs-on: ubuntu-latest
    needs: test-and-build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Log in to Google Artifact Registry
        uses: docker/login-action@v4
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build and push Docker image
        run: |
          cd app/hello_world
          docker build -t gcr.io/kanastra-dev/hello_world:${GITHUB_REF#refs/tags/} .
          docker push gcr.io/kanastra-dev/hello_world:${GITHUB_REF#refs/tags/}
